### ISSUE TITLE
Bridge: Card Play Feedback

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#56]
From a customer:

> Return the partners lead.
> 
> If a partner leads a suit which the bot takes. Follow it with a lead of the suit hoping the partner either has the next highest card or can trump the suit.

From the same person:

> Beat the lead of the partner
> 
> When NT is trump the bot is not beating the partners lead.
> 
> For example. Partner leads the 2Clubs. Opponent plays the 7 of clubs.
> 
> Bot needs to beat the 7 as high as they can.
> 
> If the bot can't beat it then it plays the lowest possible card in that suit.
> 
> The 2 of clubs was lead to setup higher cards in their hand.
> 
> By not beating the trick, nothing is being setup. It results in an easy win for the opponents.

**Comment by antross** [comment]
Both of these have been fixed by our recent improvements to the defensive play of the Bridge bots.

Bots will now return partner's initially led suit in most cases (a few special conditions take priority per discussion with some of our experts). 

The bot will now also play as high as necessary in 3rd seat, ensuring the declarer isn't handed easy tricks.
